spring:
  profiles:
    active: development
  main:
    allow-circular-references: true

---
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    hikari:
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile: development
jwt:
  secret: iC58i6J7og4Syp5/GJhakopUGezRJCTz5zQNuklSkVgQCeANA5rPYRKVGXdhiDewWfF
  lifetime: 5m


