server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    hikari:
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop


jwt:
  secret: iC58i6J7og4Syp5/GJhakopUGezRJCTz5zQNuklSkVgQCeANA5rPYRKVGXdhiDWU
  lifetime: 30m